language: python

python: 
- "3.6.6"

install:
- pip install -r requirements.txt

services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  
after_success:
- coveralls
